# Manjaro rolling release

FROM manjarolinux/base:20221028

LABEL description="QMapShack.AppImage development build"

# Update Manjaro repository and install packages
RUN	pacman -Syu --noconfirm git base-devel cmake subversion \
	qt5-base qt5-tools qt5-webengine qt5-translations wget \
	fuse2 libfbclient unixodbc libpqxx freetds \
	mariadb-clients graphicsmagick

# Install PROJ 9.1.0
# See https://proj.org/
RUN wget https://download.osgeo.org/proj/proj-9.1.0.tar.gz \
	&& tar xzvf proj-9.1.0.tar.gz \
	&& cd proj-9.1.0 \
	&& mkdir build \
	&& cd build \
	&& cmake .. -DCMAKE_INSTALL_PREFIX=/usr \
	&& cmake --build . -j$(nproc) --target install \
	&& cd / \
	&& rm -rf proj-9.1.0.tar.gz proj-9.1.0

# Install GDAL 3.5.2
# See https://gdal.org/
RUN wget https://github.com/OSGeo/gdal/releases/download/v3.5.2/gdal-3.5.2.tar.gz \
	&& tar xvzf gdal-3.5.2.tar.gz \
	&& cd gdal-3.5.2 \
	&& ./configure --prefix=/usr \
	&& make -j$(nproc) \
	&& make install \
	&& cd / \
	&& rm -rf gdal-3.5.2.tar.gz gdal-3.5.2

# Install QUAZIP 1.3
# See https://stachenov.github.io/quazip/
RUN wget https://github.com/stachenov/quazip/archive/refs/tags/v1.3.tar.gz \
	&& tar xvzf v1.3.tar.gz \
	&& cd quazip-1.3 \
	&& mkdir build \
	&& cd build \
	&& cmake .. -DCMAKE_INSTALL_PREFIX=/usr -D QUAZIP_QT_MAJOR_VERSION=5 \
	&& cmake --build . -j$(nproc) --target install \
	&& cd / \
	&& rm -rf xvzf v1.3.tar.gz quazip-1.3

# Install Routino 3.3.3
# See http://www.routino.org/
RUN svn co http://routino.org/svn/trunk routino \
	&& cd routino \
	&& sed -i '48 s|/usr/local|/usr|' Makefile.conf \
	&& make -j$(nproc) \
	&& make install	\
	&& cd / \
	&& rm -rf routino

# Install QMapShack, latest development commit
# Make only - No make install
# See https://github.com/Maproom/qmapshack
RUN git clone https://github.com/Maproom/qmapshack.git QMapShack \
	&& mkdir build_QMapShack \
	&& cd build_QMapShack \
	&& cmake ../QMapShack \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QMAPTOOL=OFF \
	&& make qmapshack -j$(nproc) \
	&& cd /

# Install AppImage
# See https://docs.appimage.org/packaging-guide/from-source/linuxdeploy-user-guide.html
RUN wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage \
	&& wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage \
	&& chmod +x linuxdeploy*.AppImage

# Copy needed PROJ, GDAL, routino, Qt data to AppDir folder
RUN mkdir -p /AppDir/usr/share /AppDir/usr/bin /AppDir/share \
	&& cp -r /usr/share/gdal /AppDir/usr/share \
	&& cp -r /usr/share/proj /AppDir/usr/share \
	&& cp -r /usr/share/routino /AppDir/usr/share \
	&& cp /usr/bin/planetsplitter /AppDir/usr/bin \
	&& cp /usr/bin/gdalbuildvrt /AppDir/usr/bin \
   	&& cp -r /usr/share/qt/translations /AppDir/usr

# Copy the needed scripts from host to root used by docker run
COPY --chown=root:root build_AppImage.sh apprun.sh /

# Docker run will open a bash as default
CMD ["/bin/bash"]

RUN echo "=====================================================" \
	&& echo "QMapShack.AppImage Docker image successfully created!" \
	&& echo "====================================================="
