# OpenSUSE 15.2 Leap

FROM opensuse/leap:15.2

LABEL description="QMapShack.AppImage development build"

# Update packages
RUN zypper refresh \
    && zypper --non-interactive update

# Install development environment
RUN zypper install -y -t pattern devel_basis

# Install needed packages
RUN zypper install -y cmake libqt5-qtbase-devel libqt5-linguist-devel \
	libqt5-qttools-devel libqt5-qtwebengine-devel proj-devel libjpeg8-devel \
	libQt5Sql5-mysql libqt5-qttranslations libbz2-devel sqlite3-devel \
	libcurl-devel libtiff-devel sqlite3 perl-GraphicsMagick wget subversion \
	git fuse-devel ghostscript ghostscript-fonts-std \
	ghostscript-fonts-std-converted

# Install PROJ 9.0.1
# See https://proj.org/
RUN wget https://download.osgeo.org/proj/proj-9.0.1.tar.gz \
	&& tar xzvf proj-9.0.1.tar.gz \
	&& cd proj-9.0.1 \
	&& mkdir build \
	&& cd build \
	&& cmake .. -DCMAKE_INSTALL_PREFIX=/usr \
	&& cmake --build . -j$(nproc) --target install \
	&& cd / \
	&& rm -rf proj-9.0.1.tar.gz proj-9.0.1

# Install GDAL 3.5.1
# See https://gdal.org/
RUN wget https://github.com/OSGeo/gdal/releases/download/v3.5.1/gdal-3.5.1.tar.gz \
	&& tar xvzf gdal-3.5.1.tar.gz \
	&& cd gdal-3.5.1 \
	&& ./configure --prefix=/usr --libdir=/usr/lib64 \
	&& make -j$(nproc) \
	&& make install \
	&& cd / \
	&& rm -rf gdal-3.5.1.tar.gz gdal-3.5.1

# Install QUAZIP 1.3
# See https://stachenov.github.io/quazip/
RUN wget https://github.com/stachenov/quazip/archive/refs/tags/v1.3.tar.gz \
	&& tar xvzf v1.3.tar.gz \
	&& cd quazip-1.3 \
	&& mkdir build \
	&& cd build \
	&& cmake .. -DCMAKE_INSTALL_PREFIX=/usr -D QUAZIP_QT_MAJOR_VERSION=5 \
	&& cmake --build . -j$(nproc) --target install \
	&& cd / \
	&& rm -rf xvzf v1.3.tar.gz quazip-1.3

# Install Routino 3.3.3
# See http://www.routino.org/
RUN svn co http://routino.org/svn/trunk routino \
	&& cd routino \
	&& sed -i '48 s|/usr/local|/usr|' Makefile.conf \
	&& sed -i '51 s|libdir=$(prefix)/lib|libdir=$(prefix)/lib64|' Makefile.conf \
	&& make -j$(nproc) \
	&& make install	\
	&& cd / \
	&& rm -rf routino

# Install QMapShack
# Based on latest development commit valid for Qt version 5.8.0
# Make only - No make install
# See https://github.com/Maproom/qmapshack
RUN git clone https://github.com/Maproom/qmapshack.git QMapShack \
	&& cd QMapShack \
	&& git checkout 269272f \
	&& cd .. \
	&& mkdir build_QMapShack \
	&& cd build_QMapShack \
	&& cmake ../QMapShack \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DBUILD_QMAPTOOL=OFF \
	&& make qmapshack -j$(nproc) \
	&& cd /

# Install AppImage
# See https://docs.appimage.org/packaging-guide/from-source/linuxdeploy-user-guide.html
RUN wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage \
	&& wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage \
	&& chmod +x linuxdeploy*.AppImage

# Copy needed PROJ, GDAL, routino, Qt data to AppDir folder
RUN mkdir -p /AppDir/usr/share /AppDir/usr/bin \
	&& cp -r /usr/share/gdal /AppDir/usr/share \
	&& cp -r /usr/share/proj /AppDir/usr/share \
	&& cp -r /usr/share/routino /AppDir/usr/share \
	&& cp /usr/bin/planetsplitter /AppDir/usr/bin \
	&& cp /usr/bin/gdalbuildvrt /AppDir/usr/bin \
   	&& cp -r /usr/share/qt5/translations /AppDir/usr

# Copy the needed scripts from host to root used by docker run
COPY --chown=root:root build_AppImage.sh apprun.sh /

# Docker run will open a bash as default
CMD ["/bin/bash"]

RUN echo "=====================================================" \
	&& echo "QMapShack.AppImage Docker image successfully created!" \
	&& echo "====================================================="
